<?php
// $Id$

/**
 * @file
 *  Settings to collapse state of panes.
 */

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function uc_checkout_pane_collapsed_form_uc_cart_checkout_form_alter(&$form, &$form_state) {
  $panes = array_filter(variable_get('uc_checkout_pane_collapsed', array()));
  // Run defined panes
  foreach ($panes as $pane) {
    if (isset($form['panes'][$pane])) {
      $form['panes'][$pane]['#collapsed'] = TRUE;
    }
  }

}

/**
 * Implementation of hook_form_FORM_ID_alter().
 *
 * Alter uc_cart_checkout_panes_form() with collapse pane selection.
 * No submission callback needed, becuase form runs system_settings_form()
 */
function uc_checkout_pane_collapsed_form_uc_cart_checkout_panes_form_alter(&$form, &$form_state) {
  $options = array();
  foreach (element_children($form['panes']) as $pane_id) {
    $options[$pane_id] = $form['panes'][$pane_id]['title']['#value'];
  }

  $form['uc_checkout_pane_collapsed'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Collapsed panes'),
    '#description' => t('Select panes to be collapsed by default on ckecout form.'),
    '#options' => $options,
    '#default_value' => variable_get('uc_checkout_pane_collapsed', array()),
  );

}