<?php
// $Id$

/**
 * @file
 *  Module to restrict exposed filter options, to the result of a view.
 *
 *  This module was inspired by views_filters_selective of views_hacks project.
 *  @see http://drupal.org/project/views_hacks
 */

/**
 * Implementation of hook_views_api().
 */
function views_frobv_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implementation of hook_form_FORMID_alter() for views_exposed_form.
 */
function views_frobv_form_views_exposed_form_alter(&$form, $form_state) {
  // Go through each filter checking for a 'frobv' setting
  foreach ($form_state['view']->filter as $field => $filter) {
    if ($filter->options['exposed']) {

      // Form element is designated by the element ID which is user-configurable
      $field_id = $form['#info']["filter-$field"]['value'];
      if (!isset($form[$field_id]['#options'])) continue;

      // If using selective filters, filter the value_options based on view results
      if ($filter->options['expose']['views_frobv'] && isset($filter->options['expose']['views_frobv_viewfield'])) {
        // Get view, display and field
        list($viewname, $display_id, $field_alias) = explode(':', $filter->options['expose']['views_frobv_viewfield']);

        $pass_arguments = ($filter->options['expose']['views_frobv_pass_arguments']);
        $pass_exposed = ($filter->options['expose']['views_frobv_pass_exposed']);

        $view = views_get_view($viewname);

        // Pass arguments to options view
        if ($pass_arguments) {
          $args = (isset($filter->view->args)) ? $filter->view->args : array();
          $view->set_arguments($args);
        }

        // Do not $_GET get passed as exposed filters values.
        if (!$pass_exposed) {
          $view->set_exposed_input(array('dummy' => TRUE));
        }
        else {
          // Use the original view's exposed input. This may lead to $_GET, if
          // there was given no other input.
          $view->set_exposed_input($filter->view->exposed_input);
        }

        // Set correct display
        $view->set_display($display_id);

        // Execute
        $view->pre_execute();
        $view->execute();

        if (!empty($view->result)) {
          if (!isset($field_alias)) {
            // Do nothing.
          }
          else {
            $options = array();
            $null_option_exists = FALSE;
            foreach ($view->result as $row) {
              if (isset($row->$field_alias)) {
                $options[$row->$field_alias] = TRUE;
              }
              else if (is_null($row->$field_alias)) {
                $null_option_exists = TRUE;
              }
            }
            if ($filter->options['expose']['optional']) {
              $options['All'] = TRUE;
            }

            // This option
            $preserve_hierarchy = (int) @$filter->options['expose']['views_frobv_preserve_hierarchy'];

            $form[$field_id]['#options'] = _views_frobv_reduce_options($form[$field_id]['#options'], array_keys($options), $preserve_hierarchy);
          }
        }
      }
    }
  }
}


/**
 * Helper function to reduce #options arrays (that can contain arrays or objects).
 * @see form_select_options()
 *
 * @param $options
 *  an options array, that can be passed to FAPI #options
 * @param $keys
 *  array of keys of the options array to reduce to.
 * @param $preserve_hierarchy
 *   hierarchy is indicated by a '-' in front of the caption. This will collide
 *   with captions that prepend '-' by itself.
 *
 * @return
 *  array of options for select & co, see FAPI #options.
 */
function _views_frobv_reduce_options($options, $keys, $preserve_hierarchy = FALSE) {

  $return_options = array();

  // Get additional keys to preserve
  if ($preserve_hierarchy) {
    $keys = _views_frobv_preserve_for_hierarchy($options, $keys, $preserve_hierarchy);
  }

  foreach ($options as $id => $option) {
    // option is an optgroup, so check the optgroup children
    if (is_array($option)) {
      $result = _views_fiters_selective_reduce_options($option, $keys);
      if (!empty($return)) $return_options[$id] = $result;
    }
    // is an object, and could contain multiple items
    else if (is_object($option)) {
      $result = _views_filters_selective_reduce_options($option->option, $keys);
      if (!empty($result)) {
        $option->option = $result;
        $return_options[$id] = $option;
      }
    }
    // default key => string relation
    else {
      if (in_array($id, $keys)) {
        $return_options[$id] = $option;
      }
    }
  }
  return $return_options;
}

/**
 * Helper function to flatten option array.
 */
function _views_frobv_flatten_options($options) {

  $flatten = array();

  foreach ($options as $id => $option) {
    // option is an optgroup, so check the optgroup children
    if (is_array($option)) {
      $result = _views_frobv_flatten_options($option);
      // no array_merge, need to preserve keys
      foreach ($result as $i => $res) {
        $flatten[$i] = $res;
      }
    }
    // is an object, and could contain multiple items
    else if (is_object($option)) {
      $result = _views_frobv_flatten_options($option->option);
      // no array_merge, need to preserve keys
      foreach ($result as $i => $res) {
        $flatten[$i] = $res;
      }
    }
    // default key => string relation
    else {
      $flatten[$id] = $option;
    }
  }
  return $flatten;
}

/**
 * Helper function to preserve child or parent entries in option array.
 */
function _views_frobv_preserve_for_hierarchy($options, $keys, $preserve_levels) {
  // Flatten all current options, and inderectly add keys due to hierarchy
  // preservation.
  if ($preserve_levels != 0) {
    $flatten = _views_frobv_flatten_options($options);

    $level = 0;
    // Levels of parents, that are automatically added on parent preservation.
    $preserved_parents = array();
    // Levels the items are automatically added, due to child preservation
    $last_found_levels = array();

    // Keys that will be added to $keys due to preservation.
    $additional_keys = array();
    $last_level = -1;
    $last_id = NULL;

    // Run each option
    foreach ($flatten as $id => $caption) {
      if ($id == 'All') continue;
      // hierarchy level of this option
      // Indicator for hierarchy is '-'.
      $this_level = strlen($caption) - strlen(ltrim($caption, '-'));

      // preserve parents
      if ($preserve_levels < 0) {
        // Not stepped up
        if ($this_level <= $last_level) {
        // Some former parents are not parents for this one anymore.
          foreach ($preserved_parents as $l => $parents) {
            if ($l >= $this_level) {
              unset($preserved_parents[$l]);
            }
          }
        }
        // Stepped up and last id is available (so not first element).
        elseif (isset($last_id)) {
          // Add former option to preservation
          $preserved_parents[$last_level][] = $last_id;
        }

        // Actual option is in keys, so some parents can go to additional keys.
        if (in_array($id, $keys)) {
          // Set parents as additional keys, that are defined levels beneath.
          foreach ($preserved_parents as $l => $parents) {
            if ($this_level - $preserve_levels > $l) {
              $additional_keys += $parents; // merge arrays
              unset($preserved_parents[$l]);
            }
          }
        }

      }
      // Preserve children
      else {
        // Actual option is in keys, further children will .
        if (in_array($id, $keys)) {
          $last_found_levels[$this_level] = $this_level;
        }
        // Stepped down or stayed, so new children available
        elseif (count($last_found_levels) && $this_level <= $last_level) {
          foreach ($last_found_levels as $lid => $level) {
            if ($lid >= $this_level) {
              unset($last_found_levels[$lid]);
            }
          }
        }
        // Level is in preserve child tolerance
        elseif (count($last_found_levels) && max($last_found_levels) + $preserve_levels >= $this_level) {
          $additional_keys[] = $id;
        }
        // stepped up and not in tolerance
        else {
          // last found levels are still valid
        }
      }

      // Set this level to next one's last level.
      $last_level = $this_level;
      $last_id = $id;
    }
    $keys = array_merge($keys, $additional_keys);

  }

  return $keys;
}


/**
 * Implementation of hook_form_FORMID_alter() for views_ui_config_item_form.
 */
function views_frobv_form_views_ui_config_item_form_alter(&$form, $form_state) {
  if (empty($form['options']['expose'])) return;

  // Is this a field we can override?
  $overrideable = array('select', 'checkboxes', 'radios');
  if (!in_array($form['options']['value']['#type'], $overrideable)) {
    return;
  }

  // Build form elements for the right side of the exposed filter form
  $right = array();

  $right['views_frobv'] = array(
    '#type' => 'checkbox',
    '#title' => t('Limit list to view result'),
    '#default_value' => @$form_state['handler']->options['expose']['views_frobv'],
    '#description' => t('If checked, the only items presented to the user will be the ones listed in the selected view\'s field.'),
  );

  $views_options = _views_frobv_view_get_options();

  $right['views_frobv_viewfield'] = array(
    '#type' => 'select',
    '#title' => t('View and field to use for limitation'),
    '#default_value' => @$form_state['handler']->options['expose']['views_frobv_viewfield'],
    '#description' => t('Select the field of a view display. It\'s result will be used to reduce this exposed filters options.'),
    '#options' => _views_frobv_view_get_options(),
    '#process' => array('views_process_dependency'),
    '#dependency' => array(
      'edit-options-expose-views-frobv' => array(1),
    ),
  );
  $right['views_frobv_pass_arguments'] = array(
    '#type' => 'checkbox',
    '#title' => t('Pass arguments to view'),
    '#default_value' =>  @$form_state['handler']->options['expose']['views_frobv_pass_arguments'],
    '#description' => t('Check this to pass the argument values of this view to the selected view.'),
    '#process' => array('views_process_dependency'),
    '#dependency' => array(
      'edit-options-expose-views-frobv' => array(1),
    ),
  );
  $right['views_frobv_pass_exposed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Pass exposed values to view'),
    '#default_value' =>  (bool) @$form_state['handler']->options['expose']['views_frobv_pass_exposed'],
    '#description' => t('Check this to pass the current views exposed filter values to the selected view.'),
    '#process' => array('views_process_dependency'),
    '#dependency' => array(
      'edit-options-expose-views-frobv' => array(1),
    ),
  );

  $options = drupal_map_assoc(range(-10,10));
  $options[0] = t('Disabled');
  $right['views_frobv_preserve_hierarchy'] = array(
    '#type' => 'select',
    '#title' => t('Preserve hierarchy'),
    '#default_value' => (int) @$form_state['handler']->options['expose']['views_frobv_preserve_hierarchy'],
    '#options' => $options,
    '#description' => t('Select the level parent or children entries are preserved in a hierarchical select.
                        So these items will be present, if they are not in the result set of the given view.
                        Level < 0 preserves levels of parents, level > 0 preserves levels of children.
                        Hierarchy levels are indicated through a \'-\'.'),
    '#process' => array('views_process_dependency'),
    '#dependency' => array(
      'edit-options-expose-views-frobv' => array(1),
    ),
  );


  $expose = $form['options']['expose'];
  $first_chunk = array_splice($expose, 0, array_search('end_checkboxes', array_keys($expose)));
  $form['options']['expose'] = array_merge($first_chunk, $right, $expose);
}

/**
 * Helper function to retrieve active views with its displays and fields.
 */
function _views_frobv_view_get_options() {
  $views = views_get_all_views();

  $options = array();

  foreach ($views as $view_name => $view) {
    if (!$view->disabled) {
      $options_view = array();
      foreach ($view->display as $display_id => $display) {

        // Return default display, for non overriden fields
        if (!isset($display->display_options['fields'])) {
          $display = $view->display;
        }
        if (isset($display->display_options['fields'])) {
          foreach ($display->display_options['fields'] as $fid => $field) {
            $val = ($field['label']) ? $field['label'] : $fid;
            $options_view["$view_name:$display_id:$fid"] = "$display_id : $val";
          }
        }
      }
      if (!empty($options_view)) {
        $options[$view_name] = $options_view;
      }
    }
  }
  return $options;
}
